# Generated by Django 4.2.26 on 2025-12-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('reconnue', models.BooleanField(default=False)),
                ('alerte', models.BooleanField(default=False)),
            ],
        ),
    ]
