# Generated by Django 4.2.26 on 2025-12-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpr', '0002_camera_plaque_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_plaque', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('chauffeur', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alpr.vehicule')),
            ],
        ),
    ]
