# Generated by Django 5.2.5 on 2025-08-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='camion_detecte',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='personnes',
        ),
    ]
