# Generated by Django 5.2.5 on 2025-09-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_status_alter_camera_zone'),
        ('mouvement', '0002_remove_mouvement_camion_detecte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='type',
        ),
        migrations.AddField(
            model_name='mouvement',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='camera.camera'),
        ),
    ]
