# Generated by Django 5.2.5 on 2025-10-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement', '0003_remove_mouvement_type_mouvement_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
