# Generated by Django 5.2.7 on 2025-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement', '0005_alter_mouvement_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
