# Generated by Django 5.2.7 on 2025-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement', '0006_alter_mouvement_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
