# Generated by Django 5.2.5 on 2025-09-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='camion.camion')),
            ],
        ),
    ]
