# Generated by Django 5.2.5 on 2025-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement_camion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcamion',
            name='type',
            field=models.CharField(choices=[('entree', 'entrée'), ('sortie', 'sortie')], default='entree'),
        ),
    ]
