# Generated by Django 5.2.5 on 2025-09-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='zone.zone'),
        ),
    ]
