# Generated by Django 5.2.5 on 2025-09-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_camera_zone'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('En maintenance', 'En maintenance'), ('En panne', 'En panne')], default='Actif'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='zone.zone'),
        ),
    ]
