# Generated by Django 5.2.5 on 2025-10-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('quai', 'Agent de quai'), ('securite', 'Sécurité')], max_length=15),
        ),
    ]
