# Generated by Django 5.2.18 on 2026-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('operateur', 'Opérateur')], default='operateur', max_length=15),
        ),
    ]
